name: Crawl and Post News

on:
  schedule:
    - cron: '0 0 * * *'
    - cron: '30 3 * * *'
    - cron: '0 7 * * *'
    - cron: '30 10 * * *'
    - cron: '0 14 * * *'
    - cron: '30 17 * * *'
    - cron: '0 21 * * *'
  
  workflow_dispatch:

jobs:
  crawl-and-post:
    runs-on: ubuntu-latest
    timeout-minutes: 200

    env:
      GEMINI_API_KEYS: ${{ secrets.GEMINI_API_KEYS }}
      GROQ_API_KEYS: ${{ secrets.GROQ_API_KEYS }}
      MISTRAL_API_KEYS: ${{ secrets.MISTRAL_API_KEYS }}
      OPENROUTER_API_KEYS: ${{ secrets.OPENROUTER_API_KEYS }}
      # Không cần set PUPPETEER_EXECUTABLE_PATH và PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install system dependencies (quan trọng)
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libnss3 \
            libatk-bridge2.0-0t64 \
            libdrm2 \
            libxkbcommon0 \
            libxcomposite1 \
            libxdamage1 \
            libxfixes3 \
            libxrandr2 \
            libgbm1 \
            libgtk-3-0t64 \
            libasound2t64 \
            libxss1 \
            fonts-liberation \
            fonts-freefont-ttf

      - name: Install npm dependencies
        run: npm ci

      - name: Run crawler
        run: node src/index.js